#!/usr/bin/env sh

# C-x to activate bindings

while read file
do
	case "$1" in
		"r")
			convert -rotate 90 "$file" "$file" ;;
		"R")
			convert -rotate -90 "$file" "$file" ;;
		"f")
			convert -flop "$file" "$file" ;;
		"y")
			echo -n "$file" | xclip -selection clipboard &&
				notify-send "$file copied to clipboard" & ;;
	esac
done
